
service: event-bridge-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements: ${file(iam-role.yml):iamRoleStatements}

functions:
  hello:
    handler: src/lambda.handler
    events:
      - http:
          path: /generate
          method: post
    environment:
      EventBusName: !Ref EventBus 

resources:
 Resources: ${file(eventBridge.yml)}
 Outputs:
    EventBusName:
      Value: !Ref EventBus
