
service: event-bridge-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements: ${file(iam-role.yml):iamRoleStatements}

functions:
  processEventLambda:
    handler: src/lambda.processMessages
    events:
      - sqs:
          arn: !GetAtt SQStopic.Arn
          batchSize: 10
          functionResponseType: ReportBatchItemFailures

  putEventLambda:
    handler: src/lambda.handler
    events:
      - http:
          path: /generate
          method: post
    environment:
      EventBusName: !Ref EventBus 

resources:
 Resources: ${file(res.yml)}
 Outputs:
    EventBusName:
      Value: !Ref EventBus
